### ISSUE TITLE
[ncrunch-vs2022] - Validation failure

### ISSUE THREAD

**Issue by BlythMeister** [hbre/chocolatey#15]
Hi your package https://community.chocolatey.org/packages/ncrunch-vs2022 has failed validation so cannot be installed :(

Can this moderation issue be resolved so i can install the package?

**Comment by hbre** [comment]
There is nothing for me to do... just wait for chocolatey Team to approve this. 

At the moment i can't even self reject https://community.chocolatey.org/packages/ncrunch-vs2022/4.10.6 this version to push the next version. 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/898832/143005398-072dbdc2-237d-4d31-977d-2a4115ba1abd.png">

**Comment by BlythMeister** [comment]
i managed to force the install :)

It does seem the verification process is not very helpful.
Thank you for trying :)

**Comment by hbre** [comment]
Version has been approved manually. Update is in queue. 

See #17 . I close this one now.
